"""
Download the Amazon-Google product-matching benchmark (Magellan / DeepMatcher).

Two independent product sources (Amazon, Google) with a gold set of matched
pairs. Matched pairs are the same product seen by both sources; their attributes
(notably price) genuinely disagree, giving real product-domain non-identifiability
witnesses — see data/amazon_google.py.

DATA AVAILABILITY / LICENSING: the Magellan benchmark datasets carry no license
(only a citation request) and are third-party product listings. We therefore
**fetch** rather than redistribute: the raw CSVs are git-ignored under
data/raw/amazon_google/ and regenerated by this script; nothing is committed or
deposited. Cite: Köpcke, Thor & Rahm, "Evaluation of entity resolution
approaches on real-world match problems", PVLDB 2010; and the Magellan project
(github.com/anhaidgroup).

Source (DeepMatcher 'Structured/Amazon-Google'): tableA=Amazon, tableB=Google,
train/valid/test carry labeled (ltable_id, rtable_id, label) pairs.

Output (written to --out-dir, default data/raw/amazon_google/):
  amazon.csv   columns: id, title, manufacturer, price
  google.csv   columns: id, title, manufacturer, price
  matches.csv  columns: amazon_id, google_id   (gold positive matches)

Usage:
  python -m data.download_amazon_google
"""

from __future__ import annotations

import argparse
import csv
import io
import urllib.request
from pathlib import Path

BASE = "https://pages.cs.wisc.edu/~anhai/data1/deepmatcher_data/Structured/Amazon-Google/exp_data"
# The file server rejects default-curl/urllib UAs; identify as a browser.
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"


def _fetch(name: str, timeout: int = 60) -> str:
    req = urllib.request.Request(f"{BASE}/{name}", headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read().decode("utf-8", errors="ignore")


def _rows(text: str) -> list[dict]:
    return list(csv.DictReader(io.StringIO(text)))


def download(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Fetching Amazon-Google tables and gold matches …")
    for src, dst in (("tableA.csv", "amazon.csv"), ("tableB.csv", "google.csv")):
        rows = _rows(_fetch(src))
        with open(out_dir / dst, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=["id", "title", "manufacturer", "price"])
            w.writeheader()
            for r in rows:
                w.writerow({k: r.get(k, "") for k in ("id", "title", "manufacturer", "price")})
        print(f"  wrote {dst} ({len(rows)} rows)")

    matches: list[tuple[str, str]] = []
    for split in ("train", "valid", "test"):
        for r in _rows(_fetch(f"{split}.csv")):
            if r.get("label") == "1":
                matches.append((r["ltable_id"], r["rtable_id"]))
    with open(out_dir / "matches.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["amazon_id", "google_id"])
        w.writerows(matches)
    print(f"  wrote matches.csv ({len(matches)} gold positive pairs)")


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Download the Amazon-Google matching benchmark")
    p.add_argument("--out-dir", type=Path, default=Path("data/raw/amazon_google"))
    args = p.parse_args(argv)
    download(args.out_dir)


if __name__ == "__main__":
    main()
