"""
Download the Fodors-Zagat restaurant-matching benchmark (Magellan / DeepMatcher).

Two independent restaurant guides (Fodors, Zagat) with a gold set of matched
pairs. Matched pairs are the same restaurant in both guides; the guides
categorize cuisine differently, giving real restaurant-domain non-identifiability
witnesses — see data/fodors_zagat.py. Tiny and clean (a third domain for breadth).

DATA AVAILABILITY / LICENSING: like Amazon-Google, the Magellan benchmark carries
no license (only a citation request) and is third-party listing data, so we
**fetch** rather than redistribute — raw CSVs are git-ignored under
data/raw/fodors_zagat/ and regenerated by this script; nothing committed/deposited.
Cite: the Magellan project (github.com/anhaidgroup); the dataset originates from
Tejada/Knoblock and is widely used as the Fodors-Zagat ER benchmark.

Source (DeepMatcher 'Structured/Fodors-Zagats'): tableA=Fodors, tableB=Zagat,
train/valid/test carry labeled (ltable_id, rtable_id, label) pairs.

Output (written to --out-dir, default data/raw/fodors_zagat/):
  fodors.csv   columns: id, name, type, phone, city
  zagat.csv    columns: id, name, type, phone, city
  matches.csv  columns: fodors_id, zagat_id   (gold positive matches)

Usage:
  python -m data.download_fodors_zagat
"""

from __future__ import annotations

import argparse
import csv
import io
import urllib.request
from pathlib import Path

BASE = "https://pages.cs.wisc.edu/~anhai/data1/deepmatcher_data/Structured/Fodors-Zagats/exp_data"
UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
COLS = ["id", "name", "type", "phone", "city"]


def _fetch(name: str, timeout: int = 60) -> str:
    req = urllib.request.Request(f"{BASE}/{name}", headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read().decode("utf-8", errors="ignore")


def _rows(text: str) -> list[dict]:
    return list(csv.DictReader(io.StringIO(text)))


def download(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Fetching Fodors-Zagat tables and gold matches …")
    for src, dst in (("tableA.csv", "fodors.csv"), ("tableB.csv", "zagat.csv")):
        rows = _rows(_fetch(src))
        with open(out_dir / dst, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=COLS)
            w.writeheader()
            for r in rows:
                w.writerow({k: r.get(k, "") for k in COLS})
        print(f"  wrote {dst} ({len(rows)} rows)")

    matches: list[tuple[str, str]] = []
    for split in ("train", "valid", "test"):
        for r in _rows(_fetch(f"{split}.csv")):
            if r.get("label") == "1":
                matches.append((r["ltable_id"], r["rtable_id"]))
    with open(out_dir / "matches.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["fodors_id", "zagat_id"])
        w.writerows(matches)
    print(f"  wrote matches.csv ({len(matches)} gold positive pairs)")


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Download the Fodors-Zagat matching benchmark")
    p.add_argument("--out-dir", type=Path, default=Path("data/raw/fodors_zagat"))
    args = p.parse_args(argv)
    download(args.out_dir)


if __name__ == "__main__":
    main()
