"""
Exhaustive identifiability verifier under relational FD semantics.

The sampling-based witness finder (data/witness.py) tests per-instance
identifiability: it looks for witnesses only among worlds generated by a
single fixed resolver.  This module tests UNIVERSAL identifiability: it
enumerates every possible world satisfying the FDs and checks whether any
observation group contains both a True and a False query instance.

The distinction matters because:
  - A resolver restricts the world space to at most d^n worlds (all
    consistent with a fixed LHS→RHS mapping).
  - Under relational FD semantics, a world is legal if every pair of
    tuples agreeing on the LHS of each FD also agrees on its RHS.
    For n_tuples=1 this is vacuous; all d^n single-row matrices are legal.
  - "Universally identifiable" means identifiable for every legal world
    pair, not just for those produced by a particular resolver.

Algorithm
---------
For n_tuples=1 (the common case in the benchmark):
  Enumerate all d^n single-row matrices (no FD filtering needed).
  Group by observation key; return the first group with Q=True and Q=False.

For n_tuples>1:
  Enumerate all d^(n_tuples*n) matrices, filter by FD satisfaction.
  Feasible for small parameters; use n_tuples=1 by default.

Parallelism
-----------
Each (config, query) pair is independent.  The module exposes
exhaustive_check_batch() which accepts a list of tasks and dispatches to
a multiprocessing pool when n_workers > 1.  For n_attrs ≤ 8 the overhead
of spawning workers exceeds the computation time; use n_workers=1.
For n_attrs ≥ 10 (≥ 59K worlds/query) parallelism pays.

Recommended chunksize = max(1, len(tasks) // (n_workers * 4)) to avoid
fine-grained task dispatch overhead.
"""

from __future__ import annotations

import itertools
import multiprocessing
from dataclasses import dataclass

import numpy as np

from .synthetic import BooleanCQ, Config, _atom_assignments, _merge
from .utils import FD, augmented_overlap
from .witness import observation_key

# ---------------------------------------------------------------------------
# CQ evaluation (resolver-free)
# ---------------------------------------------------------------------------


def evaluate_cq(cq: BooleanCQ, world: np.ndarray, config: Config) -> bool:
    """Evaluate a Boolean CQ on a world (no resolver involved)."""
    if not cq.atoms:
        return True
    assignments = _atom_assignments(cq.atoms[0], world, config)
    for atom in cq.atoms[1:]:
        if not assignments:
            return False
        next_assigns = _atom_assignments(atom, world, config)
        merged: list[dict] = []
        for a1 in assignments:
            for a2 in next_assigns:
                m = _merge(a1, a2)
                if m is not None:
                    merged.append(m)
                    break
        assignments = merged
    return len(assignments) > 0


# ---------------------------------------------------------------------------
# FD satisfaction check
# ---------------------------------------------------------------------------


def satisfies_fds(world: np.ndarray, fds: list[FD]) -> bool:
    """Return True if every pair of rows in world satisfies all FDs."""
    m = len(world)
    for lhs, rhs in fds:
        lhs_cols = sorted(lhs)
        for i in range(m):
            for j in range(i + 1, m):
                if (world[i, lhs_cols] == world[j, lhs_cols]).all():
                    if world[i, rhs] != world[j, rhs]:
                        return False
    return True


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass
class ExhaustiveResult:
    """Output of exhaustive_check for one (config, query) pair."""

    is_universally_identifiable: bool
    n_legal_worlds: int  # total worlds enumerated
    n_obs_groups: int  # distinct observation groups
    witness_w_true: list | None  # world as list-of-lists (JSON-serialisable)
    witness_w_false: list | None
    n_tuples: int


# ---------------------------------------------------------------------------
# Core exhaustive check
# ---------------------------------------------------------------------------


def exhaustive_check(
    cq: BooleanCQ,
    config: Config,
    n_tuples: int = 1,
    fast_exit: bool = True,
) -> ExhaustiveResult:
    """
    Enumerate all legal worlds and determine universal identifiability.

    fast_exit=True (default): stop as soon as a witness is found.
      n_legal_worlds will reflect how many worlds were examined before the
      witness was found, not the total count.
    fast_exit=False: enumerate all worlds (slower, gives exact group stats).
    """
    d = config.domain_size
    n = config.n_attrs
    aug_overlaps = [augmented_overlap(o, config.fds) for o in config.overlap_schemas]

    groups: dict[tuple, dict[bool, np.ndarray]] = {}
    n_worlds = 0
    witness_true: np.ndarray | None = None
    witness_false: np.ndarray | None = None

    for flat in itertools.product(range(d), repeat=n_tuples * n):
        w = np.array(flat, dtype=np.int32).reshape(n_tuples, n)

        if n_tuples > 1 and not satisfies_fds(w, config.fds):
            continue

        n_worlds += 1
        key = observation_key(w, aug_overlaps)
        q = evaluate_cq(cq, w, config)

        if key not in groups:
            groups[key] = {}
        grp = groups[key]
        if q not in grp:
            grp[q] = w.copy()

        if True in grp and False in grp and witness_true is None:
            witness_true = grp[True]
            witness_false = grp[False]
            if fast_exit:
                n_worlds_final = n_worlds
                return ExhaustiveResult(
                    is_universally_identifiable=False,
                    n_legal_worlds=n_worlds_final,
                    n_obs_groups=len(groups),  # partial count
                    witness_w_true=witness_true.tolist(),
                    witness_w_false=witness_false.tolist(),
                    n_tuples=n_tuples,
                )

    return ExhaustiveResult(
        is_universally_identifiable=witness_true is None,
        n_legal_worlds=n_worlds,
        n_obs_groups=len(groups),
        witness_w_true=witness_true.tolist() if witness_true is not None else None,
        witness_w_false=witness_false.tolist() if witness_false is not None else None,
        n_tuples=n_tuples,
    )


# ---------------------------------------------------------------------------
# Serialisation helpers for multiprocessing
# ---------------------------------------------------------------------------


def _config_to_dict(config: Config) -> dict:
    return {
        "n_attrs": config.n_attrs,
        "domain_size": config.domain_size,
        "fds": [(sorted(lhs), rhs) for lhs, rhs in config.fds],
        "view_schemas": {str(k): sorted(v) for k, v in config.view_schemas.items()},
        "overlap_schemas": [sorted(o) for o in config.overlap_schemas],
    }


def _config_from_dict(d: dict) -> Config:
    return Config(
        n_attrs=d["n_attrs"],
        domain_size=d["domain_size"],
        fds=[(frozenset(lhs), rhs) for lhs, rhs in d["fds"]],
        view_schemas={int(k): frozenset(v) for k, v in d["view_schemas"].items()},
        overlap_schemas=[frozenset(o) for o in d["overlap_schemas"]],
    )


def _cq_to_dict(cq: BooleanCQ) -> dict:

    return {"atoms": [{"view_id": a.view_id, "pattern": a.pattern} for a in cq.atoms]}


def _cq_from_dict(d: dict) -> BooleanCQ:
    from .synthetic import Atom

    return BooleanCQ(atoms=[Atom(view_id=a["view_id"], pattern=a["pattern"]) for a in d["atoms"]])


# ---------------------------------------------------------------------------
# Worker function (must be top-level for multiprocessing pickling)
# ---------------------------------------------------------------------------


def _exhaustive_worker(task: tuple) -> dict:
    """
    Multiprocessing worker.  task = (config_dict, cq_dict, n_tuples, record_id).
    Returns a result dict with record_id for reassembly.
    """
    config_dict, cq_dict, n_tuples, record_id = task
    config = _config_from_dict(config_dict)
    cq = _cq_from_dict(cq_dict)
    result = exhaustive_check(cq, config, n_tuples=n_tuples, fast_exit=True)
    return {
        "record_id": record_id,
        "exhaustive_universally_identifiable": result.is_universally_identifiable,
        "exhaustive_n_legal_worlds": result.n_legal_worlds,
        "exhaustive_n_obs_groups": result.n_obs_groups,
        "exhaustive_witness_found": result.witness_w_true is not None,
        "exhaustive_witness": {
            "w_true": result.witness_w_true,
            "w_false": result.witness_w_false,
        }
        if result.witness_w_true is not None
        else None,
        "n_tuples": n_tuples,
    }


# ---------------------------------------------------------------------------
# Batch runner
# ---------------------------------------------------------------------------


def exhaustive_check_batch(
    tasks: list[tuple],  # list of (config_dict, cq_dict, n_tuples, record_id)
    n_workers: int = 1,
    chunksize: int | None = None,
) -> list[dict]:
    """
    Run exhaustive_check on a batch of tasks.
    Uses multiprocessing when n_workers > 1.

    Recommended n_workers:
      - n_attrs ≤ 8:  use 1  (overhead > computation)
      - n_attrs = 10: use min(8, cpu_count)
      - n_attrs ≥ 12: use cpu_count
    """
    if n_workers == 1:
        return [_exhaustive_worker(t) for t in tasks]

    if chunksize is None:
        chunksize = max(1, len(tasks) // (n_workers * 4))

    with multiprocessing.Pool(processes=n_workers) as pool:
        return pool.map(_exhaustive_worker, tasks, chunksize=chunksize)
