"""
Synthetic relational world generator for identifiability experiments.

A world is an np.ndarray of shape (n_tuples, n_attrs) with int values in [0, domain_size).
Cross-world FDs are enforced via shared resolvers built once per SyntheticBenchmark instance:
each resolver is a function a-value-tuple → b-value, fixed across all worlds.

Predictor input is the overlap feature vector: probability vectors over each Õ-projection,
concatenated.  This is intentionally restricted to the closure-augmented overlap projections
(not full view contents) so that non-identifiable queries exhibit the predicted error floor.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .utils import FD, augmented_overlap, check_certificate

# ---------------------------------------------------------------------------
# Schema / configuration
# ---------------------------------------------------------------------------


@dataclass
class Config:
    n_attrs: int
    domain_size: int
    fds: list[FD]
    view_schemas: dict[int, frozenset[int]]  # view_id -> attribute set
    overlap_schemas: list[frozenset[int]]  # designated overlap attribute sets


# ---------------------------------------------------------------------------
# Query representation
# ---------------------------------------------------------------------------


@dataclass
class Atom:
    """
    One atom in a Boolean CQ: R_{view_id}(pattern).
    pattern[i] is either an int (constant constraint) or a str (variable name).
    Attributes are iterated in sorted order of the view's attribute indices.
    """

    view_id: int
    pattern: list[int | str]


@dataclass
class BooleanCQ:
    atoms: list[Atom]

    def footprint(self, config: Config) -> frozenset[int]:
        return frozenset(a for atom in self.atoms for a in config.view_schemas[atom.view_id])

    def is_certified(self, config: Config) -> bool:
        return check_certificate(self.footprint(config), config.overlap_schemas, config.fds)


# ---------------------------------------------------------------------------
# Benchmark
# ---------------------------------------------------------------------------


class SyntheticBenchmark:
    """
    Manages a fixed synthetic configuration with shared cross-world FD resolvers.
    All worlds generated by the same instance respect the same resolver maps.
    """

    def __init__(self, config: Config, seed: int = 42):
        self.config = config
        self.rng = np.random.default_rng(seed)
        self._resolvers: dict[tuple, np.ndarray] = self._build_resolvers()
        self._augmented_overlaps: list[frozenset[int]] = [
            augmented_overlap(o, config.fds) for o in config.overlap_schemas
        ]

    # ---- Resolver construction ----

    def _build_resolvers(self) -> dict[tuple, np.ndarray]:
        """
        One resolver per FD (lhs_sorted_tuple, rhs_attr) → array of size domain_size^|lhs|.
        Entry i gives the rhs value when the lhs tuple encodes to index i.
        """
        d = self.config.domain_size
        resolvers: dict[tuple, np.ndarray] = {}
        for lhs, rhs in self.config.fds:
            key = (tuple(sorted(lhs)), rhs)
            n = d ** len(lhs)
            resolvers[key] = self.rng.integers(0, d, size=n)
        return resolvers

    def _apply_resolvers(self, world: np.ndarray) -> None:
        """In-place: overwrite rhs columns using the shared resolvers."""
        d = self.config.domain_size
        for (lhs_sorted, rhs), b_vals in self._resolvers.items():
            idx = np.zeros(len(world), dtype=np.intp)
            for a in lhs_sorted:
                idx = idx * d + world[:, a].astype(np.intp)  # type: ignore[assignment]
            world[:, rhs] = b_vals[idx]

    # ---- World generation ----

    def generate_world(self, n_tuples: int) -> np.ndarray:
        """Generate one world: sample n_tuples rows then enforce FD resolvers."""
        d, n = self.config.domain_size, self.config.n_attrs
        world = self.rng.integers(0, d, size=(n_tuples, n), dtype=np.int32)
        self._apply_resolvers(world)
        return world

    def generate_worlds(self, N: int, n_tuples: int) -> list[np.ndarray]:
        return [self.generate_world(n_tuples) for _ in range(N)]

    # ---- Feature extraction ----

    def overlap_feature(self, world: np.ndarray) -> np.ndarray:
        """
        Predictor input: concatenation of empirical probability vectors over each Õ.
        Shape: (sum_O domain_size^|Õ|,) — or (1,) when no overlaps are designated.
        """
        d = self.config.domain_size
        parts: list[np.ndarray] = []
        for aug in self._augmented_overlaps:
            attrs = sorted(aug)
            n_combos = d ** len(attrs)
            counts = np.zeros(n_combos, dtype=np.float32)
            proj = world[:, attrs]
            for row in proj:
                idx = 0
                for v in row:
                    idx = idx * d + int(v)
                counts[idx] += 1.0
            parts.append(counts / len(world))
        return np.concatenate(parts) if parts else np.zeros(1, dtype=np.float32)

    def feature_dim(self) -> int:
        d = self.config.domain_size
        total = sum(d ** len(aug) for aug in self._augmented_overlaps)
        return max(total, 1)

    # ---- Query evaluation ----

    def evaluate(self, cq: BooleanCQ, world: np.ndarray) -> bool:
        """Evaluate a Boolean CQ on a world via iterative hash-join."""
        if not cq.atoms:
            return True
        assignments = _atom_assignments(cq.atoms[0], world, self.config)
        for atom in cq.atoms[1:]:
            if not assignments:
                return False
            next_assigns = _atom_assignments(atom, world, self.config)
            merged: list[dict] = []
            for a1 in assignments:
                for a2 in next_assigns:
                    m = _merge(a1, a2)
                    if m is not None:
                        merged.append(m)
                        break  # Boolean CQ — one satisfying extension is enough
            assignments = merged
        return len(assignments) > 0

    # ---- Dataset generation ----

    def make_dataset(self, cq: BooleanCQ, N: int, n_tuples: int) -> tuple[np.ndarray, np.ndarray]:
        """
        Build (X, y) where X[i] = overlap_feature(w_i), y[i] = evaluate(cq, w_i).
        X shape: (N, feature_dim).  y shape: (N,) float32 in {0.0, 1.0}.
        """
        worlds = self.generate_worlds(N, n_tuples)
        X = np.stack([self.overlap_feature(w) for w in worlds])
        y = np.array([float(self.evaluate(cq, w)) for w in worlds], dtype=np.float32)
        return X, y

    # ---- Witness construction ----

    def construct_witness(self, world: np.ndarray) -> np.ndarray | None:
        """
        Return w' ~ world by permuting values of attributes outside ∪_O Õ.
        Returns None if all attributes are grounded (witness impossible — consistent with
        identifiability being the reason, not just the specific world).
        """
        grounded = (
            frozenset().union(*self._augmented_overlaps)
            if self._augmented_overlaps
            else frozenset()
        )
        free = [a for a in range(self.config.n_attrs) if a not in grounded]
        if not free:
            return None
        w_prime = world.copy()
        perm = self.rng.permutation(self.config.domain_size)
        for a in free:
            w_prime[:, a] = perm[w_prime[:, a]]
        self._apply_resolvers(w_prime)  # re-enforce FDs on rhs attributes
        return w_prime


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _atom_assignments(atom: Atom, world: np.ndarray, config: Config) -> list[dict]:
    """
    Return all variable assignments (var_name -> value dicts) consistent with the
    constant constraints in atom.pattern for tuples in atom's view.
    """
    attrs = sorted(config.view_schemas[atom.view_id])
    proj = world[:, attrs]
    results: list[dict] = []
    for row in proj:
        assign: dict = {}
        ok = True
        for pat, val in zip(atom.pattern, row.tolist()):
            val = int(val)
            if isinstance(pat, int):
                if val != pat:
                    ok = False
                    break
            else:  # variable name (str)
                if pat in assign and assign[pat] != val:
                    ok = False
                    break
                assign[pat] = val
        if ok:
            results.append(assign)
    return results


def _merge(a1: dict, a2: dict) -> dict | None:
    """Merge two variable assignments; return None on conflict."""
    merged = dict(a1)
    for k, v in a2.items():
        if k in merged and merged[k] != v:
            return None
        merged[k] = v
    return merged
