"""
Generate pgfdata for the real-world §5/§6 result tables from committed result
JSONs — so nothing in the paper is hand-transcribed.

Covers three experiments (latest run of each):
  * e_realworld_witnesses  -> realworld_witnesses.{csv,tex}  (certified/witness per query)
  * e_minaug_realworld     -> minaug_realworld.{csv,tex}     (MinAug prescriptions)
  * e_witness_discovery    -> witness_discovery.csv          (CrossKG discovery stats)

(The ML benchmark table is generated separately by analysis/export_realworld_ml.py.)

Usage:
    python -m analysis.export_realworld_tables
    python -m analysis.export_realworld_tables --output-dir ../paper/pgfdata
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
from pathlib import Path

DATASET_LABELS = {
    "bibinteg": "BibInteg",
    "wdc": "WDC-Product",
    "crosskg_dblp": "CrossKG-DBLP",
    "amazon_google": "Amazon--Google",
    "fodors_zagat": "Fodors--Zagat",
}
DATASET_ORDER = ["bibinteg", "wdc", "crosskg_dblp", "amazon_google", "fodors_zagat"]


def _latest(results_dir: Path, pattern: str) -> str | None:
    files = glob.glob(str(results_dir / pattern))
    return max(files, key=os.path.getmtime) if files else None


def _order_key(ds: str) -> int:
    return DATASET_ORDER.index(ds) if ds in DATASET_ORDER else 99


def _ds(ds: str) -> str:
    return DATASET_LABELS.get(ds, ds)


def _write_csv(path: Path, cols: list[str], rows: list[dict]) -> None:
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in cols})
    print(f"Wrote {path}")


# ---------------------------------------------------------------------------
# e_realworld_witnesses  (RQ2: certified vs. real witness per query)
# ---------------------------------------------------------------------------


def export_witnesses(results_dir: Path, output_dir: Path) -> None:
    f = _latest(results_dir, "e_realworld_witnesses_*.json")
    if not f:
        return
    results = sorted(
        json.load(open(f))["results"], key=lambda r: (_order_key(r["dataset"]), r["query"])
    )
    rows = [
        {
            "dataset": r["dataset"],
            "query": r["query"],
            "certified": r["certified"],
            "witness_found": "" if r["certified"] else bool(r.get("witness_found")),
            "scan_position": r.get("n_records_scanned") if not r["certified"] else "",
            "n_obs_groups": r.get("n_obs_groups") if not r["certified"] else "",
        }
        for r in results
    ]
    _write_csv(
        output_dir / "realworld_witnesses.csv",
        ["dataset", "query", "certified", "witness_found", "scan_position", "n_obs_groups"],
        rows,
    )

    def status(r: dict) -> str:
        if r["certified"]:
            return "certified (no witness)"
        if r.get("witness_found"):
            return f"witness @ {r['n_records_scanned']}"
        return "no witness found"

    lines = [
        "% Generated by analysis/export_realworld_tables.py — do not edit by hand.",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "Dataset & Query & Result \\\\",
        "\\midrule",
    ]
    prev = None
    for r in results:
        ds = _ds(r["dataset"]) if r["dataset"] != prev else ""
        prev = r["dataset"]
        q = r["query"].replace("_", "\\_")
        lines.append(f"{ds} & \\texttt{{{q}}} & {status(r)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    (output_dir / "realworld_witnesses.tex").write_text("\n".join(lines))
    print(f"Wrote {output_dir / 'realworld_witnesses.tex'}")


# ---------------------------------------------------------------------------
# e_minaug_realworld  (RQ3: minimum augmentation prescribed per query)
# ---------------------------------------------------------------------------


def _actions_str(selected: list) -> str:
    return ", ".join("{" + ",".join(str(a) for a in act) + "}" for act in selected) or "--"


def export_minaug(results_dir: Path, output_dir: Path) -> None:
    f = _latest(results_dir, "e_minaug_realworld_*.json")
    if not f:
        return
    results = sorted(
        json.load(open(f))["results"], key=lambda r: (_order_key(r["dataset"]), r["query"])
    )
    rows = [
        {
            "dataset": r["dataset"],
            "query": r["query"],
            "certified_before": r["certified_before"],
            "n_actions": r["n_actions_greedy"],
            "added_attrs": _actions_str(r["selected_actions"]),
            "verified_certified_after": r["verified_certified_after"],
            "greedy_time_us": r["greedy_time_us"],
        }
        for r in results
    ]
    _write_csv(
        output_dir / "minaug_realworld.csv",
        [
            "dataset",
            "query",
            "certified_before",
            "n_actions",
            "added_attrs",
            "verified_certified_after",
            "greedy_time_us",
        ],
        rows,
    )

    lines = [
        "% Generated by analysis/export_realworld_tables.py — do not edit by hand.",
        "% added_attrs are attribute indices added to the overlap (see each dataset's schema).",
        "\\begin{tabular}{llccc}",
        "\\toprule",
        "Dataset & Query & Certified? & \\#Actions & Added attrs \\\\",
        "\\midrule",
    ]
    prev = None
    for r in rows:
        ds = _ds(r["dataset"]) if r["dataset"] != prev else ""
        prev = r["dataset"]
        q = r["query"].replace("_", "\\_")
        cert = "yes" if r["certified_before"] else "no"
        lines.append(
            f"{ds} & \\texttt{{{q}}} & {cert} & {r['n_actions']} & {r['added_attrs']} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    (output_dir / "minaug_realworld.tex").write_text("\n".join(lines))
    print(f"Wrote {output_dir / 'minaug_realworld.tex'}")


# ---------------------------------------------------------------------------
# e_witness_discovery  (RQ2 quantification: CrossKG discovery-rate stats)
# ---------------------------------------------------------------------------


def export_witness_discovery(results_dir: Path, output_dir: Path) -> None:
    f = _latest(results_dir, "e_witness_discovery_crosskg_*.json")
    if not f:
        return
    cols = [
        "query",
        "n_records",
        "positive_rate",
        "frac_found",
        "median_position",
        "pct10_position",
        "pct90_position",
        "frac_within_50",
        "frac_within_100",
        "frac_within_200",
        "frac_within_500",
        "frac_within_1000",
    ]
    rows = [{k: r.get(k) for k in cols} for r in json.load(open(f))["results"]]
    _write_csv(output_dir / "witness_discovery.csv", cols, rows)


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Generate pgfdata for the real-world result tables")
    p.add_argument("--results-dir", type=Path, default=Path("results"))
    p.add_argument("--output-dir", type=Path, default=Path("pgfdata"))
    args = p.parse_args(argv)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    export_witnesses(args.results_dir, args.output_dir)
    export_minaug(args.results_dir, args.output_dir)
    export_witness_discovery(args.results_dir, args.output_dir)


if __name__ == "__main__":
    main()
