"""
Export the real-world ML benchmark (e4) results as a pgfdata CSV for the paper.

Reads the timestamped e4_realworld_*.json result files, keeps the cross-source
matched-pair datasets, aggregates balanced accuracy over seeds per
(dataset, query, architecture), and writes a single CSV that the paper's
LaTeX renders directly (e.g. via pgfplotstable) — no manual transcription.

Usage:
    python -m analysis.export_realworld_ml
    python -m analysis.export_realworld_ml --results-dir results --output-dir pgfdata
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import statistics
from collections import defaultdict
from pathlib import Path

# The cross-source matched-pair datasets (default selection).
DATASETS = ["crosskg_dblp", "amazon_google", "fodors_zagat"]
DATASET_LABELS = {
    "crosskg_dblp": "CrossKG-DBLP",
    "amazon_google": "Amazon--Google",
    "fodors_zagat": "Fodors--Zagat",
}
# Display order for the table: feature-reading models first, then the rest.
ARCH_ORDER = [
    "mlp",
    "set_transformer",
    "vanilla_overlap",
    "gnn_og",
    "closure_aware",
    "majority_vote",
]
ARCH_LABELS = {
    "mlp": "MLP",
    "set_transformer": "SetTransformer",
    "vanilla_overlap": "VanillaOverlap",
    "gnn_og": "GNN-OG",
    "closure_aware": "Closure-Aware",
    "majority_vote": "MajorityVote",
}


def collect(results_dir: Path, datasets: list[str]) -> list[dict]:
    """Aggregate mean/std balanced accuracy over seeds per (dataset, query, model)."""
    bucket: dict[tuple, list[float]] = defaultdict(list)
    meta: dict[tuple, bool] = {}
    for fpath in glob.glob(str(results_dir / "e4_realworld_*.json")):
        with open(fpath) as fh:
            for r in json.load(fh).get("results", []):
                if r["dataset"] not in datasets:
                    continue
                key = (r["dataset"], r["query"], r["model"])
                bucket[key].append(float(r["test_balanced_accuracy"]))
                meta[(r["dataset"], r["query"])] = bool(r["certified"])

    rows: list[dict] = []
    for (ds, q, model), accs in sorted(bucket.items()):
        rows.append(
            {
                "dataset": ds,
                "query": q,
                "query_type": "certified" if meta[(ds, q)] else "uncertified",
                "architecture": model,
                "bal_acc_mean": round(statistics.mean(accs), 4),
                "bal_acc_std": round(statistics.pstdev(accs), 4) if len(accs) > 1 else 0.0,
                "n_seeds": len(accs),
            }
        )
    return rows


def write_tex(rows: list[dict], out: Path, datasets: list[str]) -> None:
    """Emit a ready-to-\\input booktabs tabular (archs x dataset{C,U}) from `rows`.
    Cells >= 0.99 are bolded. Layout only — all numbers come from `rows`."""
    acc = {(r["dataset"], r["query_type"], r["architecture"]): r["bal_acc_mean"] for r in rows}
    archs = [a for a in ARCH_ORDER if any(r["architecture"] == a for r in rows)]

    def cell(ds: str, qt: str, a: str) -> str:
        v = acc.get((ds, qt, a))
        if v is None:
            return "--"
        return f"\\textbf{{{v:.2f}}}" if v >= 0.99 else f"{v:.2f}"

    lines = [
        "% Generated by analysis/export_realworld_ml.py — do not edit by hand.",
        "% C = certified query, U = uncertified query (per dataset).",
        "\\begin{tabular}{l" + "cc" * len(datasets) + "}",
        "\\toprule",
        " & "
        + " & ".join(f"\\multicolumn{{2}}{{c}}{{{DATASET_LABELS.get(d, d)}}}" for d in datasets)
        + " \\\\",
        " ".join(f"\\cmidrule(lr){{{2 * i + 2}-{2 * i + 3}}}" for i in range(len(datasets))),
        "Architecture & " + " & ".join("C & U" for _ in datasets) + " \\\\",
        "\\midrule",
    ]
    for a in archs:
        cells = []
        for d in datasets:
            cells += [cell(d, "certified", a), cell(d, "uncertified", a)]
        lines.append(f"{ARCH_LABELS.get(a, a)} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    out.write_text("\n".join(lines))
    print(f"Wrote {out}")


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Export e4 real-world ML results to pgfdata CSV")
    p.add_argument("--results-dir", type=Path, default=Path("results"))
    p.add_argument("--output-dir", type=Path, default=Path("pgfdata"))
    p.add_argument("--datasets", nargs="+", default=DATASETS)
    args = p.parse_args(argv)

    rows = collect(args.results_dir, args.datasets)
    if not rows:
        raise SystemExit(
            f"No e4_realworld_*.json records for {args.datasets} in {args.results_dir}"
        )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    out = args.output_dir / "realworld_ml.csv"
    cols = [
        "dataset",
        "query",
        "query_type",
        "architecture",
        "bal_acc_mean",
        "bal_acc_std",
        "n_seeds",
    ]
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)
    print(
        f"Wrote {out} ({len(rows)} rows: "
        f"{len({r['dataset'] for r in rows})} datasets x "
        f"{len({r['architecture'] for r in rows})} architectures)"
    )
    # Also emit a ready-to-\input tabular (layout from the same data).
    present = [d for d in args.datasets if any(r["dataset"] == d for r in rows)]
    write_tex(rows, args.output_dir / "realworld_ml.tex", present)


if __name__ == "__main__":
    main()
